//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Здания.
    /// </summary>
    // *** Start programmer edit section *** (Здания CustomAttributes)

    // *** End programmer edit section *** (Здания CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗданияE", new string[] {
            "Номер as \'Номер\'"})]
    [View("ЗданияL", new string[] {
            "Номер as \'Номер\'"})]
    public class Здания : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        // *** Start programmer edit section *** (Здания CustomMembers)

        // *** End programmer edit section *** (Здания CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Здания.Номер CustomAttributes)

        // *** End programmer edit section *** (Здания.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Здания.Номер Get start)

                // *** End programmer edit section *** (Здания.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Здания.Номер Get end)

                // *** End programmer edit section *** (Здания.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Здания.Номер Set start)

                // *** End programmer edit section *** (Здания.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Здания.Номер Set end)

                // *** End programmer edit section *** (Здания.Номер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗданияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗданияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗданияE", typeof(IIS.Proba2.Здания));
                }
            }
            
            /// <summary>
            /// "ЗданияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗданияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗданияL", typeof(IIS.Proba2.Здания));
                }
            }
        }
    }
}
